### PR TITLE
Fix/url value object

### PR DESCRIPTION
**Pull request by ArturHamannRonconi**
I'm making this pull request, with a small change in the code, I changed the regex of the url value object so that it can include urls in the local environment, such as http://localhost:4000

Captura de tela de 2023-01-11 10-52-11

### CODE REVIEW

**Comment by 4lessandrodev** [comment]
#221

**Comment by 4lessandrodev** [comment]
Hey @ArturHamannRonconi thanks so much to contribute with types-ddd lib 🥇 .

Could you add a test for the invalid url case? For example:

```ts

const valueObject = UrlValueObject.create('invalid-url');

```

What will be the result?

Thanks!!!

**Comment by ArturHamannRonconi** [comment]
All right, sorry for the delay in making the change, but I believe that now it is working as expected, I used the URL object as mentioned.

I only have one observation, in the last commit I made I modified some things in the unit tests, some functions that did not exist and were missing and I commented some parts of the code, however, I left all these changes in a commit in case you want to `git revert` it

with this pull request closes #222

**Comment by 4lessandrodev** [comment]
@ArturHamannRonconi tests for `password.value-object` fails.

Could you please update "rich-domain" dep and check the test fot `password.value-object` and update this pull request?

**Pull request merged**
